name: CI
on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Build & Unit Tests
        run: ./gradlew clean assembleDebug testDebugUnitTest --stacktrace

      - name: Static Analysis (Detekt, Ktlint, Lint)
        run: |
          ./gradlew detekt ktlintCheck lintVitalRelease

      - name: Upload Lint Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports
          path: app/build/reports/**
